
<?php  $_gridrecords = $block->getCollection(); // get collection which we set in block class ?>
<?php if ($_gridrecords && count($_gridrecords)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('ID #') ?></th>
                    <th scope="col" class="col title"><?php echo __('Title') ?></th>
                    <th scope="col" class="col date"><?php echo __('Publish Date') ?></th>
                    <th scope="col" class="col status"><?php echo __('Status') ?></th>
                    <th scope="col" class="col actions"><?php echo __('Action') ?></th>
                    <th scope="col" class="col ">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php  // read collection as magento1.x and display in list 
                       foreach ($_gridrecords as $_gridrecord): ?>
                    <tr>
                        <td class="col id"><?php echo $_gridrecord->getId() ?></td>
                        <td class="col shipping"><?php echo $_gridrecord->getTitle() ?></td>
                        <td class="col date"><?php echo $block->formatDate($_gridrecord->getPublishDate()) ?></td>
                        <td class="col status"><?php echo $_gridrecord->getIsActive() ?></td>
                        <td class="col actions" data-th="Actions">
<a class="action view" href="<?php echo $this->getUrl('excellence/test/edit'); ?>id/<?php echo $_gridrecord->getId() ?>/">
<span>Edit</span>
</a>
<a class="action order" href="<?php echo $this->getUrl('excellence/index/delete'); ?>id/<?php echo $_gridrecord->getId() ?>/">
<span>Delete</span>
</a>
                       </td>
                       
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('grid records not available.'); ?></span></div>
<?php endif ?>


<form method="POST" action="<?php echo $this->getUrl('excellence/index/post'); ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'> 


<fieldset class="fieldset">
        
        <div class="field note no-label"><?php echo __('Add record to table') ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?php echo __('Title') ?></span></label>
            <div class="control">
                <input name="title" id="title" title="<?php echo __('Title') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field is_active required">
            <label class="label" for="is_active"><span><?php echo __('Status') ?></span></label>
            <div class="control">
                <input name="is_active" id="is_active" title="<?php echo __('Status') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="actions-toolbar">
	        <div class="primary">
	            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
	                <span><?php echo __('Submit') ?></span>
	            </button>
	        </div>
    	</div>
</fieldset>
	

</form>
